### ISSUE TITLE
Visual Studio not rendering >= and <= properly

### ISSUE THREAD

**Issue by BradKnowles** [eigilnikolajsen/commit-mono#24]
`>=`  and `<=` are rendering strangely in Visual Studio 2022 on Windows.   The font has been customized with both ligatures and arrows.  Visual Studio Code seems to display correctly.

The code sample
```
var y = travelTime.Month >= 11 || travelTime.Month <= 12;
var x = 1 <= 3;
```
Visual Studio 2022
![image](https://github.com/eigilnikolajsen/commit-mono/assets/1277856/4440568b-c41e-493f-9ae5-0906c83d1d13)

VS Code
![image](https://github.com/eigilnikolajsen/commit-mono/assets/1277856/814d48fb-9dec-4752-a9f4-cee32cbcf3f9)

**Comment by eigilnikolajsen** [comment]
That's odd. I'll have a look into why this might be. The weirdest thing to me is the fact that the `var x = 1 <= 3` renders correctly.

**Comment by eigilnikolajsen** [comment]
Hello, can I have you try this on the latest version? I just released a new version 1.133 where I flipped those features, so hopefully it should work optimally now.

**Comment by BradKnowles** [comment]
I’ve been out of town the last few days, I’ll give it a try this week and report back. Thank you!

**Comment by BradKnowles** [comment]
I'm using 1.134 and am experiencing some oddities in spacing now.

Alts is using all download features and Alt a, Alt G, Alt 6 and 9, and Lifted *

Alts2 is just using all download features and no alternate characters.

Download weight, letter spacing, and line height are all defaults, 450, 0%, and 1.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/1277856/f3469653-2591-49c7-a277-62f51827b3c1)

**Comment by eigilnikolajsen** [comment]
Sorry for the inconveniency, a bug slipped out. The weird vertical metrics have been fixed, so if you don't mind, it'd love for you to try again, to see if the ligatures work now.

**Comment by BradKnowles** [comment]
Thanks, the vertical issues have been fixed, but unfortunately I still see the same thing in Visual Studio.  It works if numbers are on both sides of the <= but as soon as any letters appear, it switches to the full arrow.

**Comment by eigilnikolajsen** [comment]
That is very odd. I will see what I can do. Thank you for testing!

**Comment by BradKnowles** [comment]
I re-tested with 1.138 still seeing the same results.  Here is my `custom-settings.json` so you know what options I've used.

```json
{
  "weight": 400,
  "italic": false,
  "alternates": {
    "cv01": true,
    "cv02": true,
    "cv03": false,
    "cv04": true,
    "cv05": true,
    "cv06": false,
    "cv07": false,
    "cv08": false,
    "cv09": false
  },
  "features": {
    "ss01": true,
    "ss02": true,
    "ss03": true,
    "ss04": true,
    "ss05": true
  },
  "letterSpacing": 0,
  "lineHeight": 1
}
```

**Comment by BradKnowles** [comment]
@eigilnikolajsen 1.139 seems to have resolved this issue.  Doing more testing across different machines and configurations, but so far so good.

**Comment by eigilnikolajsen** [comment]
Great to hear, thank you for testing!

**Comment by BradKnowles** [comment]
Closing issue.  1.139 has been working great in Visual Studio with no further issues.

**Comment by eigilnikolajsen** [comment]
Great, thank you.
